version: "2"
linters:
  default: none
  enable:
    # Duplicate word usage, such as 'and and' in a comment.
    - dupword
    - errcheck
    # Type assertion and comparison validation on errors. https://github.com/polyfloyd/go-errorlint
    - errorlint
    - gocritic
    - gosec
    - govet
    - ineffassign
    - iotamixing
    # Check for simple misspellings of words. 
    - misspell
    - nestif
    - nilerr
    - nilnesserr
    # Require explanations for nolint comments
    - nolintlint
    - prealloc
    # Overwriting predeclared Golang names such as 'len' and 'min'.
    - predeclared
    # Validate common mistakes in Golang, such as invalid time.Parse format, invalid regular expression, etc.
    - staticcheck
    - unparam
    # Unused constants, variables, functions and types
    - unused
  settings:
    errorlint:
      errorf: false
    gocritic:
      disabled-checks:
        - assignOp
        - appendAssign
        - captLocal 
        - commentFormatting 
        - elseif
        - exitAfterDefer
        - ifElseChain
        - sloppyLen
        - underef
        - unslice
    govet:
      # The following list includes all the linters that are disabled by default.
      # Uncomment any of these to enable them:
      enable:
        - atomicalign          # Check for non-64-bits-aligned arguments to sync/atomic functions
        - deepequalerrors      # Check for calls of reflect.DeepEqual on error values
        - fieldalignment       # Find structs that would use less memory if their fields were sorted
        - findcall             # Find calls to a particular function
        - nilness              # Check for redundant or impossible nil comparisons
        - reflectvaluecompare  # Check for comparing reflect.Value values with == or reflect.DeepEqual
        - shadow               # Check for possible unintended shadowing of variables
        - sortslice            # Check the argument type of sort.Slice
        - timeformat           # Check for calls of (time.Time).Format or time.Parse with 2006-02-01
        - unusedwrite          # Check for unused writes
    nestif:
        # Minimal complexity of if statements to report.
        min-complexity: 4
    nolintlint:
      # Disable to ensure that all nolint directives actually have an effect.
      # Default: false
      allow-unused: false
      # Exclude following linters from requiring an explanation.
      # Default: []
      allow-no-explanation: [dupWord]
      # Enable to require an explanation of nonzero length after each nolint directive.
      # Default: false
      require-explanation: true
      # Enable to require nolint directives to mention the specific linter being suppressed.
      # Default: false
      require-specific: true
    staticcheck:
      checks:
        ["all"]
    unparam:
          # Inspect exported functions.
          #
          # Set to true if no external program/library imports your code.
          # XXX: if you enable this setting, unparam will report a lot of false-positives in text editors:
          # if it's called for subdir of a project it can't find external interfaces. All text editor integrations
          # with golangci-lint call it on a directory with the changed file.
          #
          # Default: false
          check-exported: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
